- config.c
- include/config.h
- lldp_dcbx_cfg.c
This patch allows lldpad to use any network interface name.
Right now lldpad does not accept interface names containing non
alphanumeric characters (except '_' and '-'). As Markus Mehlan reported
(http://lists.open-lldp.org/pipermail/lldp-devel/2017-March/001251.html)
this is a constraint originally from libconfig.
Libconfig manual states that:
*http://www.hyperrealm.com/libconfig/libconfig_manual.html
"All names are case-sensitive. They may consist only of
alphanumeric characters, dashes (‘-’), underscores (‘_’), and
asterisks (‘*’), and must begin with aletter or asterisk. No
other characters are allowed."
Given this restriction we thought the best idea would be to interact
with libconfig using a "sanitized" version of the interface name. The
names in this patch are generated using the …
> Use interface index instead of name in libconfig

- lldp_8021qaz.c
- lldp_evb.c
- lldp_evb22.c
Most of the TLV modules that have an rchange handler for received TLVs
seem to get the return values wrong, returning 0 or TLV_OK without
freeing or storing the unpacked TLV to be freed later. That leaks the
allocation, as rxProcessFrame believes the module has claimed ownership.
In a test setup, it's probably easiest to see by enabling some TLV type
on one side of a connection only.  Or, any unexpected TLV that doesn't
get handled will be erroneously leaked by the EVB modules.
> memleak on received TLVs from modules

- lldp_dcbx_cmds.c
Added a return value check for 'set_dcb_state'. The function
didn't check whether the 'set_hw_state' was successful.
Without this check 'dcb sc <if> dcb [on/off]' returns 'Successful'
even when operation is not supported in driver.
Fixes: 527ac435e46c ("lldpad: Do not enable CEE mode if explicitly disabled")
Signed-off-by: Shay Agroskin <shayag@mellanox.com>
> DCB set state operation return value check

- qbg/ecp22.c
When a link is shut, an ecp22 and l2_packet_data structure is removed for
the corresponding interface. l2_packet_data has a socket that needs to be
closed via l2_packet_deinit before the ecp22 structure can be freed.
Failure to close the socket causes a segfault once lldpad has exceeded the
maximum open file descriptors.
> ecp22: deinit l2_packet_data before freeing ecp22

- lldp_8021qaz_clif.c
According to 802.1qaz standard the length of the Application
Priority Table is stored in a 9 bit variable. Current function
ieee8021qaz_print_app_tlv uses an 8 bit integer to iterate over
the table. This commit changes the iterator to a 16 bit integer.
> Fix application tlv display

- lldp_8021qaz_cmds.c
The P802.1Qcd/D2.1 standard draft introduces a new APP TLV: DSCP, with
selector value of 5. Don't reject APP TLV's with selector 5, and
sanitize the PID value to not be out of bounds for DSCP.
Signed-off-by: Petr Machata <petrm@mellanox.com>
> lldpad: Support DSCP selectors in APP TLV's

- lldp_8021qaz.c
This merge contains only changes to honor willing value from config file; The default willing value (which is enabled) has not been changed. 
There are two commits in this merge:
189f63a - 8021qaz: Honor willing value from config file
Read the willing value of pfc and ets variables directly from the config file before calling set_ieee_hw. In case such value exists and its value is false, then we don't set any pfc/ets data to write to hw.
59c9a54 - 8021qaz: Remove unused variable
Previous commit had introduced an unused variable.
> Persistent willing2

- lldpad.service
- lldpad.socket
Add missing rules in file lldpad.service:
- Requires=lldpad.socket   # Bring up socket when service goes up
- Restart=always           # Attempt to start service when is down
and missing information in file lldpad.socket:
- Add [Unit] section with description of socket
> rpm: Add fields to *.service and *.socket files

- include/lldp_basman_clif.h
- lldp_basman_cmds.c
Add functions [get, set, test]_arg_info in lldp_basman_cmds.c to
allow users to get or set the value of optional lldp TLVs.
Optional tlvs are (lldptool tlv name inside brackets):
[portDesc] Port description
[sysName] System name
[sysDesc] System description
[sysCap] System capabilities
[mngAddr] Management address
The format to modify a TLV content is:
lldptool -i <ifname> -T -V sysDesc info="New Value"
> lldp: Allow lldptool to modify optional TLV's content

- lldp_8021qaz_clif.c
- test-driver
Following definition of DSCP APP TLV with selector 5, print dscp2prio
map for DSCP APP entries instead of printing them as any other APP
entry.
DSCP standard 802.1Qcd-2015/D.2.15.3
> 8021qaz: Print dscp2prio map

- lldp_8021qaz.c
- lldp_mand_cmds.c
- lldpad.c
Add parameter passive_8021qaz to change 8021qaz module behavior
with respect to hw values. If passive_8021qaz is true, then hw
values will be updated/modified. If passive_dcbx is false, then
there will be no changes to hw.
To run in passive mode use -P option: 'lldpad -P'
> 8021qaz: Add parameter passive_8021qaz to run in read only mode

- vdptool.c
vdptool.c was generating an error: implicit declaration for the
getline() function.
Signed-off-by: Laurent Charpentier <laurent_pubs@yahoo.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/open-lldp/0001-vdptool-fixed-compile-error-for-getline.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> vdptool: fixed compile error for getline()

- lldp_util.c
- qbg/ecp22.c
First is a fix to the lldp_util routine when pulling address information.
Second is a fix to the ecp22 module under error conditions.
Neither has been tested thoroughly.
> Two bug fixes

- event_iface.c
When a port is enslaved to a bridge, the kernel will emit multiple
RTM_NEWLINK messages for the port when the bridge device is brought down
and then up. Assuming 'swp3' is enslaved to 'br0', the following link
events will be generated when 'br0' is toggled:
```
9: swp3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br0 state UP
link/ether 7c:fe:90:ff:27:d1
31: br0: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default
link/ether 7c:fe:90:ff:27:d1 brd ff:ff:ff:ff:ff:ff
9: swp3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br0 state UP
link/ether 7c:fe:90:ff:27:d1
9: swp3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br0 state UP
link/ether 7c:fe:90:ff:27:d1
31: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state DOWN group default …
```
> lldpad: Do not enable port if already enabled

- lldp_dcbx_nl.c
- qbg/vdp.c
- qbg/vdpnl.c
These are some static analysis and compiler warning fixes.
Tested with clang and gcc.  There are additional issues around enum conversion, but I'll submit them separately for evaluation.
> Misc static analysis fixes

- .travis.yml
- contrib/build-rpm.sh
This branch adds in support to run a build and test on OpenLLDP automatically through Travis CI. If enabled on the main repo, this should help ensure pull requests actually compile and pass some level of testing first.
> Travis CI Integration

- lldp/l2_packet.h
ETH_P_LLDP is now defined in if_ether.h on new kernels. Guarding this prevents
double definition when building on 5.3 kernels.
Signed-off-by: Scott Register <sreg@sreg.io>
> l2_packet: Guard ETH_P_LLDP define

- lldp_dcbx.c
The dcbx_data function can return a null pointer, but the dcbx tlv function
will happily attempt to dereference.  Prevent this by checking for result
and bailing.
Fixes: a37b7e0f3b66 ("lldpad: initial git commit")
> dcbx: check for dcbx_data result

- lldp_8021qaz.c
Two patches were added to try and honor the
willing value for ets and pfc from the config
file.  This change caused lldpad to stop
accepting new configurations from the commnad
line tools after the first configuration.
Backing out these two patches to restore
functionality of lldpad.
Hashes of patches being reverted:
59c9a549831ad9bd3baac0d88dce2f724e045113
"8021qaz: Remove unused variable"
189f63a0b72bdd70710bfcce2a104e0ad7e915c1
"8021qaz: Honor willing value from config file"
Signed-off-by: Dave Ertman <david.m.ertman@intel.com>
Change-type: Other
Title: Revert patches attemping to honor config file
> 8021qaz: Revert patches attemping to honor config file

- config.c
- lldp_8021qaz.c
- lldp_8023.c
- lldp_dcbx.c
- lldp_dcbx_cfg.c
- qbg/ecp.c
A handful of error messages are missing newlines which messes up the prompt.
> Print newline for all error messages

- dcbtool_cmds.c
- lldptool_cmds.c
Fixed 'unknown type pid_t' gcc compile error in dcbtool_cmds.c and
lldptool_cmds.c
Signed-off-by: Laurent Charpentier <laurent_pubs@yahoo.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/open-lldp/0004-fixed-unknown-type-pid_t.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> fixed unknown type pid_t

- Makefile.am
Add a convenience target to build RPMs for easier testing.
> lldpad: add 'make rpm'

- lldp/rx.c
The state machine might have called 'DELETE' just before RX got
triggered, so we might end up having no frame to process.
If so just ignore this packet.
Signed-off-by: Hannes Reinecke <hare@suse.de>
> lldp: do not call 'assert' in rxProcessFrame()

- .travis.yml
Note gcc-10 checks are being done on Bionic instead of Focal since there is a
bug in Focal's version of gcc-10 (at time of writing) which was reporting false 
failures: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94647
Signed-off-by: Scott Register <scottx.register@intel.com>
> travis-ci: Add gcc10 check

- event_iface.c
- include/qbg_vdpnl.h
Instead of always setting the receive buffer size
to a small 8K, which causes problems when a flood of
netlink messages are received, set it to a
"minimal" value only if it is currently less
than that value.
The value used is 32 x the MAX_PAYLOAD size
of 4k, i.e. 128k.
A config value to modify this can be added if needed,
but doesn't seem warranted at this time.
Changes in V2:
* remove unneeded debugging/logging
> event_iface: only set rcv buf size if too small

- lldp/agent.c
- lldp/states.h
- lldp/tx.c
Currently, lldpad correctly transmits a shutdown pdu with ttl = 0s when
transitioning from rxtx or txonly to rxonly.  However, when we shutdown
lldpad it will transmit a shutdown pdu even if the port is configured
to rxonly mode.  For some implementations of LLDP this can create
a confusing state and lead to issues in the network.  Correct this by
only transmitting a shutdown PDU when going from any transmit mode to
a receive only mode, and don't transmit PDUs on shutdown if the port
agent isn't configured to transmit.
Reported-by: Matthew Whitehead <mwhitehe@redhat.com>
Reported-at: https://bugzilla.redhat.com/show_bug.cgi?id=1905210
> tx: when operating in rx-only mode don't send a port shutdown pdu

- lldp_8021qaz.c
- lldp_8021qaz_clif.c
- lldp_util.c
- qbg/vdp22_cmds.c
After a quick run through coverity and GCC's experimental scanner, a number of
issues were flagged.  While some were false positives, on some closer looks, it seems
that some are real issues.  None seem to be security issues, but all need to be addressed.
The bulk are errors during error processing.  These should almost never occur, but we fix
them here.
> Static analysis scan fixes

- lldp_basman.c
The managed address pulling routine will fail to reset the return
value from a previous attempt if no IPv4 and IPv6 addresses are
available.  Use the return address of the hwaddr fetch.
Resolves: https://github.com/intel/openlldp/issues/82
> basman: use return address when pulling address

- config.c
- include/config.h
- lldp_dcbx_cfg.c
This reverts commit e272d34f45bc15d52424228f824c1ad96932867e.
During production, it was found that the ifindex can be unstable.
See discussion at https://github.com/intel/openlldp/pull/3
> Revert "Use interface index instead of name in libconfig"

- .github/workflows/build.yml
This is part of the efforts to improve the total OpenSSF score.
> Restrict CI build to read-only GitHub permissions
